constraints:
  day_min_interval: 14
  night_cooldown_days: 2
  night_min_interval_weeks: 7
members:
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: true
  name: 丸岡
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: false
  name: 今井
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: true
  name: 加藤凌
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: false
  name: 加藤貴
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: false
  name: 勅使河原
- active: true
  assignable_day1: false
  assignable_day2: true
  assignable_night: false
  name: 斉藤
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: true
  name: 新井洋
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: false
  name: 新井翔
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: true
  name: 木村
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: true
  name: 楮本
- active: true
  assignable_day1: false
  assignable_day2: true
  assignable_night: true
  name: 田中
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: true
  name: 矢野
- active: true
  assignable_day1: false
  assignable_day2: true
  assignable_night: true
  name: 隝田
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: true
  name: 高橋拓
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: false
  name: 高橋良
- active: true
  assignable_day1: true
  assignable_day2: true
  assignable_night: false
  name: 髙田
schedule:
  day_shift_weekdays:
  - 5
  - 6
  night_shift_start_weekday: 0
